### ISSUE TITLE
"Unrecognized resource type" when used with DigitalOcean

### ISSUE THREAD

**Issue by cowwoc** [pulumi/pulumi-command#554]
### What happened?

Given:
```
const swarmInit = new remote.Command("swarmInit", {
	connection: {
		host: managerDroplet.ipv6Address,
		user: "redacted",
		privateKey
	},
	create: "hostname"
}, {provider});
```

I get:
> error: unrecognized resource type (Check): command:remote:Command

### Example

N/A

### Output of `pulumi about`

```
CLI          
Version      3.138.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  command       1.0.1
resource  digitalocean  4.34.0
resource  docker        4.5.7
language  nodejs        unknown

Host     
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in nodejs: executable='C:\Users\Gili\scoop\apps\nodejs\current\node.exe' version='v23.2.0'

Current Stack: licensed/licensed/staging

TYPE                                URN
pulumi:pulumi:Stack                 urn:pulumi:staging::licensed::pulumi:pulumi:Stack::licensed-staging
pulumi:providers:digitalocean       urn:pulumi:staging::licensed::pulumi:providers:digitalocean::digitalocean
digitalocean:index/droplet:Droplet  urn:pulumi:staging::licensed::digitalocean:index/droplet:Droplet::swarm-manager


Found no pending operations associated with staging

Backend
Name           pulumi.com
URL            https://app.pulumi.com/cowwoc
User           cowwoc
Organizations  cowwoc, licensed
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cowwoc** [comment]
It's odd. If I remove the DigitalOcean `provider`, the command seems to work, but if I add it back it fails. I would love for this to work with the provider because I want to explicitly target where each command is getting executed...

**Comment by cowwoc** [comment]
Actually, the `connection` argument already specifies where the command will execute... but it's odd/inconsistent that one can specify `provider` for all other Pulumi APIs but not this one...

**Comment by mjeffryes** [comment]
Thanks for sharing this @cowwoc. The `provider` parameter on a resource is designed to allow you to create resources with different provider configurations in the same program. Eg. you might want to create resources in two different AWS regions or two different kubrerneties clusters in the same program, since those properties are configured on the provider, you need to explicitly indicate which provider to use when creating the resource.

So the error message arises from the fact that you passed a provider for DigitalOcean resources to a resource from the "Command" provider; and the Digital Ocean provider had no idea what "command:remote:Command" means. We have an issue open to improve this error message so it's less confusing! https://github.com/pulumi/pulumi/issues/7105
